version: '2'
services:
    web:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/code
        depends_on:
            - couchdb
    couchdb:
        image: couchdb
        environment:
            COUCHDB_USER: admin
            COUCHDB_PASSWORD: admin
        ports:
            - "5984:5984"


